### ISSUE TITLE
DGNSS gives false positive RTK-FIXED

### ISSUE THREAD

**Issue by chrisriteco** [mtz8302/AOG_Dual_GPS#4] opened 2020-10-12 20:12 UTC
In the U-Center I have a 3D / DGNSS-Fix (no DGPS) with a 3D quality of approximately 0.5 m. This is without NTRIP or RTCM from the BASE, but AOG indicates that there is an RTK-FIX . RTK-FIX is cm accurate in my experience, so something is not going well in the translation from MTZ to AG.

**Comment by mtz8302** [comment] 2020-10-13 18:16
Hi,
the ESP code transfers the flags in the PVT sentence into GGA flags. The problem is, that they are not matching really good. In my case they seem to work, but the problem was allread reported by others. At the moment I have no time to do anything about it. The code is in the NMEA tab line 185ff. So please check if you can fix it.

greetings
Matthias

**Comment by mtz8302** [comment] 2020-12-05 20:56
fixed by using the "real" GGA sentence for it
Thanks to ai

**Closed as completed by mtz8302** 2020-12-05 20:56 UTC
